//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1120342HW4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iPhone
    {
        public int Id { get; set; }
        public string type { get; set; }
        public string price { get; set; }
        public string wafer { get; set; }
        public string weight { get; set; }
        public string battery { get; set; }
    }
}
